# Generated by Django 5.2.6 on 2025-09-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('service', models.CharField(choices=[('general_checkup', 'General Checkup'), ('cleaning', 'Teeth Cleaning'), ('filling', 'Dental Filling'), ('extraction', 'Tooth Extraction'), ('crown', 'Dental Crown'), ('root_canal', 'Root Canal Treatment'), ('orthodontics', 'Orthodontics Consultation'), ('cosmetic', 'Cosmetic Dentistry'), ('emergency', 'Emergency Treatment'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-created_at'],
            },
        ),
    ]
